#!/bin/sh
set -e

# Automatically added by dh_python3
if command -v py3compile >/dev/null 2>&1; then
	py3compile -p python3-grinder-touch 
fi
if command -v pypy3compile >/dev/null 2>&1; then
	pypy3compile -p python3-grinder-touch  || true
fi

# End automatically added section
# Automatically added by dh_icons/13.11.4
if [ "$1" = "configure" ] || [ "$1" = "abort-upgrade" ] || [ "$1" = "abort-deconfigure" ] || [ "$1" = "abort-remove" ] ; then
	if command -v update-icon-caches >/dev/null; then
		update-icon-caches /usr/share/icons/bg.png /usr/share/icons/down_arrow.png /usr/share/icons/down_arrow_disabled.png /usr/share/icons/left_arrow.png /usr/share/icons/left_arrow_disabled.png /usr/share/icons/right_arrow.png /usr/share/icons/right_arrow_disabled.png /usr/share/icons/up_arrow.png /usr/share/icons/up_arrow_disabled.png
	fi
fi
# End automatically added section
