# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/home/chris/SurfaceGrinder-linuxcnc-ui/debian/python3-semiauto-surfacegrinder/usr/lib/python3.11/dist-packages/widgets/mk_dro/mk_dro.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(276, 79)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Form.sizePolicy().hasHeightForWidth())
        Form.setSizePolicy(sizePolicy)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(Form)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.frame = QtWidgets.QFrame(Form)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.axis_actions_button = QtWidgets.QPushButton(self.frame)
        self.axis_actions_button.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.axis_actions_button.sizePolicy().hasHeightForWidth())
        self.axis_actions_button.setSizePolicy(sizePolicy)
        self.axis_actions_button.setIconSize(QtCore.QSize(48, 48))
        self.axis_actions_button.setObjectName("axis_actions_button")
        self.horizontalLayout.addWidget(self.axis_actions_button)
        self.dro_entry = DROLineEdit(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.dro_entry.sizePolicy().hasHeightForWidth())
        self.dro_entry.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Sans")
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.dro_entry.setFont(font)
        self.dro_entry.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.dro_entry.setProperty("referenceType", 1)
        self.dro_entry.setProperty("axisNumber", 0)
        self.dro_entry.setProperty("latheMode", 0)
        self.dro_entry.setObjectName("dro_entry")
        self.horizontalLayout.addWidget(self.dro_entry)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setSizeConstraint(QtWidgets.QLayout.SetMinimumSize)
        self.verticalLayout.setObjectName("verticalLayout")
        self.homed_indicator = QtWidgets.QLabel(self.frame)
        self.homed_indicator.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.homed_indicator.setPixmap(QtGui.QPixmap("/home/chris/SurfaceGrinder-linuxcnc-ui/debian/python3-semiauto-surfacegrinder/usr/lib/python3.11/dist-packages/widgets/mk_dro/icons/homed.png"))
        self.homed_indicator.setAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.homed_indicator.setObjectName("homed_indicator")
        self.verticalLayout.addWidget(self.homed_indicator)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.horizontalLayout.addLayout(self.verticalLayout)
        self.horizontalLayout_2.addWidget(self.frame)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.axis_actions_button.setText(_translate("Form", "X"))
        self.dro_entry.setText(_translate("Form", "0.000"))
        self.dro_entry.setProperty("inchFormat", _translate("Form", "%.4f"))
        self.dro_entry.setProperty("millimeterFormat", _translate("Form", "%.3f"))
        self.dro_entry.setProperty("degreeFormat", _translate("Form", "%.2f"))
from qtpyvcp.widgets.input_widgets.dro_line_edit import DROLineEdit
